#!/usr/bin/env python3
"""Render the onset provenance registry from the ground truth.

Every lead-time figure in the paper is measured against the onset stored in
`validation/gt_events.json`, so those dates are the measurement instrument and
need the same provenance discipline as any other input. This script renders them
as a human-readable registry, with the verification status, the evidence used to
fix the date, and the registered source where one exists.

It does not verify anything itself. Verification is a judgement call backed by a
source, and the outcome is recorded in the ground-truth fields:

    onset_status           verified | draft-needs-verification | confirmed-known
    onset_evidence         prose statement of what the source says
    onset_source           URL, when a specific source is registered
    onset_source_accessed  ISO date on which that URL was checked

Usage
-----
  python3 analysis/onset_registry.py                       # markdown to stdout
  python3 analysis/onset_registry.py --out reports/onset_registry.md
  python3 analysis/onset_registry.py --check               # audit, non-zero on gaps
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GT = ROOT / "validation" / "gt_events.json"

OK_STATUS = "verified"


def load() -> list[dict]:
    d = json.loads(GT.read_text(encoding="utf-8"))
    return sorted(d["events"], key=lambda e: e["gt_onset_date"])


def render_markdown(events: list[dict]) -> str:
    out = ["# Onset provenance registry", "",
           "Generated by `analysis/onset_registry.py` from `validation/gt_events.json`.",
           "Every lead-time figure in the paper is measured against these dates.", "",
           f"Events: {len(events)}. Verified: "
           f"{sum(1 for e in events if e.get('onset_status') == OK_STATUS)}. "
           f"With a registered source URL: "
           f"{sum(1 for e in events if e.get('onset_source'))}.", ""]
    for e in events:
        out.append(f"## {e['event_id']}")
        out.append("")
        out.append(f"- event: {e.get('event_name', '')}")
        out.append(f"- onset: **{e['gt_onset_date']}**")
        out.append(f"- status: `{e.get('onset_status', 'MISSING')}`")
        out.append(f"- evidence: {e.get('onset_evidence', '')}")
        if e.get("onset_source"):
            out.append(f"- source: {e['onset_source']} "
                       f"(accessed {e.get('onset_source_accessed', 'n/a')})")
        else:
            out.append("- source: no URL registered; see evidence")
        out.append("")
    return "\n".join(out)


def render_latex(events: list[dict]) -> str:
    """Compact appendix table: event, onset, status, registered source."""
    def esc(s: str) -> str:
        for a, b in (("&", r"\&"), ("_", r"\_"), ("%", r"\%"), ("#", r"\#")):
            s = s.replace(a, b)
        return s

    lines = [r"\begin{tabular}{llll}", r"\toprule",
             r"event & onset & status & source \\", r"\midrule"]
    for e in events:
        name = esc(e.get("event_name") or e["event_id"])
        src = e.get("onset_source")
        if src:
            # shorten a DOI/URL to its host + last path segment for the table
            tail = src.rstrip("/").split("/")[-1]
            host = src.split("//")[-1].split("/")[0]
            src = esc(f"{host}/…/{tail}")
        else:
            src = "see registry"
        lines.append(f"{name} & {e['gt_onset_date']} & {e.get('onset_status','')} & {src} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def check(events: list[dict]) -> int:
    bad = 0
    for e in events:
        s = e.get("onset_status")
        if s != OK_STATUS:
            print(f"  [{s}] {e['event_id']} — {e['gt_onset_date']}")
            bad += 1
    if not bad:
        print(f"  all {len(events)} onsets carry status '{OK_STATUS}'")
    nosrc = [e["event_id"] for e in events if not e.get("onset_source")]
    print(f"  {len(nosrc)} of {len(events)} have no registered source URL")
    return bad


def main() -> int:
    ap = argparse.ArgumentParser(description="onset provenance registry")
    ap.add_argument("--out", default="")
    ap.add_argument("--latex", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    events = load()
    if args.check:
        print("onset registry audit:")
        return 1 if check(events) else 0

    text = render_latex(events) if args.latex else render_markdown(events)
    if args.out:
        p = ROOT / args.out
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text + "\n", encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
